### ISSUE TITLE
People

### ISSUE THREAD

**Issue by kigos21** [TomasinoWeb/tomasinoWebR101#95]

**Comment by kigos21** [comment]
## Notes on The People page

I don't know at what breakpoint size should I use the "Desktop" design. I made some adjustments of my own as to when the "Desktop" layout should be used

In the "17 Years" section, **I used the full resolution images** since I cannot get the layer to export without the dark grey borders. I believe that this is not the best decision since the images will take a longer time to load on slower network connections.

I also added a prop `customClasses` for `Button` component in `Buttons.tsx`. I needed to overwrite some styling.

### Accomplished
- everything but the Core Reel part

### To Follow
- The Core Reel component (need help on this one from `py16` branch)

### For Confirmation
- are the styles satisfactory across all device sizes?

**Comment by scinscinscin** [comment]
Fixed, closing.
